export const affirmations = [
  ["this found you for a reason", "take a slow breath before you keep scrolling"],
  ["you didn't tap this by accident", "notice one thing around you right now"],
  ["pause — this moment matters", "unclench your jaw for a second"],
  ["something here is meant for you", "stay here 5 seconds longer"],
  ["you're allowed to take your time", "slow down one thing you're doing"],
  ["you're doing better than you think", "think of one small thing you handled today"],
  ["it's okay to not have clarity yet", "stop trying to figure everything out right now"],
  ["you can rest without falling behind", "relax your shoulders for a moment"],
  ["not everything needs to make sense right now", "let one question go unanswered"],
  ["you're still allowed to try again", "pick one tiny next step"],
  ["feeling lost doesn't mean you are", "take one steady breath in and out"],
  ["you don't need to rush your becoming", "resist the urge to hurry for a minute"],
  ["something is already working in your favor", "trust one instinct today"],
  ["you're closer than it feels", "keep going for just 10 more seconds"],
  ["trust yourself a little more today", "make one small decision without overthinking"],
  ["you're allowed to take up space", "sit or stand a little more openly"],
  ["you're becoming someone you needed before", "appreciate how far you've come"],
  ["this version of you is not final", "imagine one thing that could change"],
  ["growth can feel like confusion at first", "be okay with not knowing yet"],
  ["you're allowed to outgrow what once fit", "release one thing you've been holding onto"],
  ["your pace is not your failure", "do one thing at whatever speed feels right"],
  ["you are not too much", "take up a little more room today"],
  ["the quiet moments count too", "sit in this silence for just a breath"],
  ["you've been carrying a lot", "put one thing down, even briefly"],
  ["it's okay to feel more than one thing at once", "name what's heaviest right now"],
  ["you don't have to be fixed to be worthy", "offer yourself a little grace today"],
  ["your tiredness is information, not weakness", "rest before you think you need to"],
  ["you are allowed to want things", "name one thing you're quietly hoping for"],
  ["the hard parts are making you something", "find one small proof that you're growing"],
  ["you showed up today, that matters", "acknowledge yourself for being here"],
  ["it's okay to need more time", "stop rushing this one moment"],
  ["you are not behind", "let go of one timeline that isn't yours"],
  ["your feelings are data, not drama", "let yourself feel what's actually here"],
  ["something soft is trying to reach you", "breathe into wherever you feel tight"],
  ["you don't have to earn rest", "close your eyes for just one breath"],
  ["you're more resilient than you remember", "recall one hard thing you already survived"],
  ["even this uncertainty is part of it", "stay with the unknown for just a moment"],
  ["you're not falling apart, you're rearranging", "allow one thing to be in progress"],
  ["gentleness is not the same as giving up", "be soft with yourself right now"],
  ["you are allowed to change your mind", "let go of one decision you've been forcing"],
  ["your presence is enough", "just be here, nothing more needed"],
  ["the fog will lift when it's ready", "stop trying to see the whole path"],
  ["you are worthy of what you're asking for", "say yes to one small thing for yourself"],
  ["this too is part of the journey", "accept where you are right now"],
  ["you can feel scared and still move forward", "take one small step despite the fear"],
  ["the version of you that made it is real", "picture who you're becoming"],
  ["rest is how you refill", "give yourself permission to stop for a moment"],
  ["you are not your worst day", "remember one day that felt lighter"],
  ["asking for help is not weakness", "think of one person you could lean on"],
  ["your story isn't over", "turn the page gently in your mind"],
  ["you deserve the kindness you give others", "say something gentle to yourself"],
  ["you are still allowed to hope", "name one thing you're still hoping for"],
  ["the small things you do matter", "think of one quiet good thing you did lately"],
  ["you are held, even when it doesn't feel like it", "feel the ground beneath you right now"],
  ["something in you already knows the way", "listen to your gut for just a second"],
  ["you don't have to have it all together", "let one thing be messy for now"],
  ["healing isn't linear and that's okay", "be kind to the part of you still learning"],
  ["you were built for more than productivity", "exist without an agenda for one breath"],
  ["not every day needs to be a win", "let today be enough as it is"],
  ["you are more than your output", "step away from what you're trying to achieve for a moment"],
  ["your sensitivity is a superpower", "honor one feeling instead of pushing it away"],
  ["you're allowed to grieve what didn't work out", "make space for something that didn't go as planned"],
  ["your body is working hard for you", "thank it for one thing right now"],
  ["the right things will find their way", "release one outcome you've been gripping"],
  ["you are not alone in this", "remember someone else has felt exactly this"],
  ["stillness is not the same as being stuck", "allow this pause to be intentional"],
  ["you have more courage than you admit", "name one brave thing you did recently"],
  ["this is a moment you'll have moved through", "remind yourself that this is temporary"],
  ["you are allowed to start again from here", "begin again with just one small action"],
  ["you don't have to perform being okay", "drop the mask just for this moment"],
  ["the answer might come through rest", "stop searching and just be still"],
  ["your longing is pointing you somewhere", "follow one thread of what you truly want"],
  ["you are worthy of good things arriving", "open yourself to receiving something good"],
  ["you made it to this moment", "let that be enough for now"],
  ["let your nervous system settle", "breathe out slower than you breathe in"],
  ["you are not required to be everything", "release one role you're trying to fill perfectly"],
  ["it's okay to be in the middle", "stop waiting to be finished to feel okay"],
  ["your needs are not inconvenient", "honor one need you've been ignoring"],
  ["you've survived every difficult moment so far", "remember your own track record"],
  ["you are allowed to feel joy too", "let yourself smile at one small thing"],
  ["the cracks are where the light gets in", "find one small beauty in what's broken"],
  ["you can change direction at any time", "consider one small pivot that might help"],
  ["you matter beyond what you produce", "exist without justifying yourself for a moment"],
  ["your softness is not a liability", "let your guard down just a little"],
  ["you are exactly where you need to be", "trust the timing of your life right now"],
  ["your effort is seen, even when unspoken", "acknowledge your own quiet dedication"],
  ["you are allowed to move slowly", "do the next thing at half speed"],
  ["something is shifting even when you can't see it", "trust the invisible progress"],
  ["you are enough as you are right now", "stop adding conditions to your own worth"],
  ["it's okay to feel more than you show", "let something surface without judgment"],
  ["you deserve your own patience", "extend yourself the same grace you'd give a friend"],
  ["the world is better with you in it", "let that truth land for just a second"],
  ["you don't have to earn love", "receive care without deflecting it today"],
  ["you are building something real", "name one piece of it that already exists"],
  ["you are braver than you believe", "do one thing today that takes quiet courage"],
  ["even resting is an act of trust", "let yourself stop without guilt"],
  ["your future self is rooting for you", "make one choice they'd be proud of"],
  ["you are already on your way", "keep going, one breath at a time"],
]

export function getShuffled() {
  const copy = [...affirmations]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

// Module-level cache: EchoPage writes this, ReflectPage reads it as a fallback.
// Survives navigation within the same tab session.
let _currentAffirmation = null

export function setCurrentAffirmation(pair) { _currentAffirmation = pair }
export function getCurrentAffirmation()     { return _currentAffirmation || affirmations[0] }
